steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-c-docker.pkg.dev/argon-triode-335914/quickstart-docker-repo/quickstart-image:tag1', '.' ]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/argon-triode-335914/imagem-do-projeto:tag"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-resource-file
  - --image=gcr.io/argon-triode-335914/imagem-do-projeto:tag
  - --location=us-central1-c
  - --cluster=quickstart-cluster-project-nuvem-cluster



# - name: "gcr.io/cloud-builders/docker"
#   args: ["build", "-t", "gcr.io/argon-triode-335914/imagem-do-projeto:tag", "."]