steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/argon-triode-335914/imagem-do-projeto:tag", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/argon-triode-335914/imagem-do-projeto:tag"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=/manifest
  - --image=gcr.io/argon-triode-335914/imagem-do-projeto:tag
  - --location=us-central1-c
  - --cluster=quickstart-cluster-project-nuvem-cluster
